#!/usr/bin/env sh

main() {
  logfile='__dir__.log'
  git_branch='dirlog'

  if [ ! -d ./.git  ]; then
    _create_repo
  elif [ $(_another_repo_exists) ]; then
      echo '[INFO] Skipped. Already a git repository.'
      exit
  else
    _update_repo
  fi
}

_create_repo() {
  git init
  git commit --allow-empty -m "init"
  touch .gitignore
  echo '*' >> .gitignore
  echo '!'$logfile >> .gitignore
  echo '!.git*' >> .gitignore
  git add .gitignore
  git commit -m "Ignores all the files in the directory except for the dir.log"
  git branch -M $git_branch
}

_another_repo_exists() {
  current_git_branch=$(git branch | grep \* | cut -d ' ' -f2)
  [ $current_git_branch != $git_branch ] && echo 1
}

_update_repo() {
  ls -l > $logfile
  git add $logfile
  git commit -m 'AUTO: made by `dirlog`'
}

main
